import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Nav } from '../components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Creative Operations Platform for Creative Teams | Air - Takehome',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  )
}
